### ISSUE TITLE
design ui & flow  정리

### ISSUE THREAD

**Issue by soyalattee** [StockmonGo/FE-stockmon#69]
## ✅ 해야 할 작업을 TASK 별로 작성해주세요.
- [ ] 전체화면일때 UI 맞추기 
- [ ] 페이지간 라우팅 월드에서 도감, 알림, 마이페이지, 동맹

<br><br>

**Comment by 777Naity** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer
